### ISSUE TITLE
I need a guide and the video

### ISSUE THREAD

**Issue by hppedeaf** [adeleine1412/leapmotion-osc#6]
I don't understand follow your guide, I tried install node and command 'npm start' but still not work

**Comment by philippgitpush** [comment]
Heya! Have you tried running `npm install` before you run `npm start`?

Please also note that this is more of a proof of concept. At the moment, only the fingers (opening and closing) can be tracked with this.

**Comment by hppedeaf** [comment]
I downloaded leapjs and node-osc then I open node command 'npm install' image, then npm start and it is error

![image](https://user-images.githubusercontent.com/79153226/190708874-41229939-1e89-46bd-8a4a-0f62b8ecb383.png)

**Comment by philippgitpush** [comment]
Have you downloaded leapjs and node-osc manually? If so, you don't need to! You just need a clean copy of this project and `npm install` should install leapjs and node-osc for you automatically.

**Comment by hppedeaf** [comment]
ok, after how start osc leapmotion ?

**Comment by philippgitpush** [comment]
Make sure your cmd.exe is in the right directory, from the looks of the screenshot you are in `C:\Users\hppedeaf` you should be in `C:\Users\hppedeaf\leapmotion-osc-release-1.0.2\` or something like that. Open the "leapmotion-osc-release-1.0.2" folder, SHIFT + RIGHT CLICK on an empty spot an choose "Open PowerShell window here". Now in that new window run `npm install` & `npm start`.

![image](https://user-images.githubusercontent.com/53810001/190712429-4eb39f41-aa74-416b-a3b2-cbef67af4754.png)

![image](https://user-images.githubusercontent.com/53810001/190712514-826a5bd0-3e1b-4534-9a07-ccd2f2b7b33f.png)

You can also try copying the path to the folder and typing `cd <path>` (e.g: `cd C:\Users\adeleine\Desktop\leapmotion-osc-release-1.0.2` in my case)

**Comment by hppedeaf** [comment]
ah finally! I do it too different on you, thank you very much! and I ask you question? you can add system rotation? how i explain . You will understand with these images, so I want to be able to sign ^^ thank you!

![image](https://user-images.githubusercontent.com/79153226/190717437-78dd86d7-3c09-4009-b925-0ef36b24a63b.png)
![image](https://user-images.githubusercontent.com/79153226/190717502-0c182bb5-05eb-4aa4-8e02-e0742652fb2b.png)

**Comment by philippgitpush** [comment]
That is exactly what I meant! At the moment there is only opening/closing of the fingers. Moving the fingers left/right or spreading the fingers is not added. I will probably look into this in the future, but you can expect this to take up twice as many avatar parameters as it does now.

Unfortunately, I can't give you a time estimate on this because I'm working on paid projects at the moment that take up most of my development time. In the next version I want to upgrade to Leapmotions latest driver (`v3.2.1` to `v5.6.1`) which has much better finger tracking, but that is a very big change. Seeing that someone in the HH community is interested motivates me to continue working on it!

Will keep you informed when there is an update. But for now you can maybe look into this:
https://github.com/SDraw/driver_leap

**Comment by hppedeaf** [comment]
Hi,
ooh, it's good that you know the HH (helping hands) community, I'm in that situation.

ok on moving the fingers left/right takes more parametres but can you two groups of low parametres and high parametres?

I tried on vrchat with leapmotion but not working ... I use controller index I saw osc code in vrchat debug it even works I added my gesture avatar from your prefabs and I have tested in unity osc it works!

**Comment by philippgitpush** [comment]
When changing any parameter on your avatar you have to make sure to reset your OSC config, you can do that in-game and if that doesn't work you will also need to delete all the folders it generates in `C:\Users\adeleine\AppData\LocalLow\VRChat\VRChat\OSC` (everytime in VRChat you load an avatar, it will create a config but it will never update, so you need to delete all folders inside it)

Sometimes the in-game reset option doesn't work, so that is why you need to delete the folder manually and then reload your avatar. The reason it works in unity is because with Lyumas Av3Emulator it generates a config everytime yo go into test/play mode.

The config is pretty much just a list of all the parameters your avatar has.

![image](https://user-images.githubusercontent.com/53810001/190900624-d94936fc-dea4-4b0b-b413-bd3d840d0703.png)

**Comment by hppedeaf** [comment]
okay, thanks for the help!

**Comment by philippgitpush** [comment]
There is now a new standalone version that does not need NodeJS or a terminal to run it. It has an executable .exe file that you can simply launch.

You will need to update to **Gemini 5.7.2** [here](https://developer.leapmotion.com/tracking-software-download), mare sure to remove / uninstall the old `Orion 3.2.1` Driver.
Avatar setup is the same, there is no finger spreading yet but the update to the new driver (3.2.1 to 5.7.2) with better tracking.

[LeapmotionOSC version 1.0.3](https://github.com/adeleine1412/leapmotion-osc/releases/tag/release-1.0.3).
(Download `
leapmotionosc-1.0.3-windows.exe` or `leapmotionosc-1.0.3-windows.zip`)

![image](https://user-images.githubusercontent.com/53810001/191484217-bc658006-b500-4db6-b796-2b3e35b583cc.png)

**Comment by philippgitpush** [comment]
Closing to avoid confusion as the new version no longer runs on NodeJS

**Comment by ThatGuyThimo** [comment]
@hppedeaf  Finger spread has been added in the newest [release](https://github.com/adeleine1412/leapmotion-osc/releases/tag/release-1.1.0).
