### ISSUE TITLE
finger spread

### ISSUE THREAD

**Issue by somecat2015r** [adeleine1412/leapmotion-osc#8]
![f2](https://user-images.githubusercontent.com/64453996/204938693-4b792155-bcf1-49ee-b97a-0e4ab57698af.PNG)
![f](https://user-images.githubusercontent.com/64453996/204938705-a99f6294-2e95-4ea5-b010-20572bd42d59.PNG)
https://github.com/SDraw/ml_mods_vrc
it used to be have one
simple  plug and use 
and one day vrc decide to kill every mod
i already have valve index but i still want leap and finger spread on it
sorry for bothering you and stealing photo form some weird site
i know nothing about coding :/

**Comment by philippgitpush** [comment]
Not planning to add this yet, but a lot of development is being made towards OSC, OSC-Query, and OSC-Trackers, which might open up a way to move finger tracking to NetIK (Faster update rate than the laggy 10HZ we have right now). If not, I will add finger spreading manually since we now have double the parameter count.

Previous thread, follow this for updates on it:
https://github.com/adeleine1412/leapmotion-osc/issues/6#issuecomment-1249741040

**Comment by ThatGuyThimo** [comment]
@somecat2015r  Finger spread has been added in the newest [release](https://github.com/adeleine1412/leapmotion-osc/releases/tag/release-1.1.0).
